### ISSUE TITLE
[ Customize Panel ] Load decoration icon svg / png

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#103]
- [x] allow user to load icon in svg that is behind to category/tag name (mekong eye). It could be png to make this process easier.
![image](https://user-images.githubusercontent.com/12487823/89706484-8ae8d000-d93c-11ea-92b5-1cda4de12387.png)
![image](https://user-images.githubusercontent.com/12487823/90649006-95467c00-e210-11ea-82b1-9113e02fcdf0.png)

- [x] The post's configuration must have 3 options only for featured image: large, behind and hidden.
![image](https://user-images.githubusercontent.com/12487823/89907044-87ff1100-dbc2-11ea-8029-e73a077078b1.png)

![image](https://user-images.githubusercontent.com/12487823/90647891-39c7be80-e20f-11ea-9375-927a3e5bde69.png)

- [x] In Customize Panel: The post's configuration must have 3 options only for featured image: large, behind and hidden.
![image](https://user-images.githubusercontent.com/12487823/90647983-59f77d80-e20f-11ea-92f2-a551c33b0c23.png)

**Comment by isaquemelo** [comment]
feature/panel-options
