### ISSUE TITLE
[ Dark mode ] minor fixes - p2

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#116]
- [x] meta-info in Related posts has opacity 1% so, it doesn't appear in light mode
![image](https://user-images.githubusercontent.com/12487823/89701669-81953e80-d90f-11ea-83c7-7e810bbb79fb.png)

- [x] The erro console continues appearing
![image](https://user-images.githubusercontent.com/12487823/89701749-3e879b00-d910-11ea-8ed9-ec36114522f8.png)
here: https://mekongeye-jeo.hacklab.com.br/type/2020/08/what-is-geography-wide-layout/

- [x] Fix Opinion title for dark mode. There is no layout so we can decide which fix apply to.
![image](https://user-images.githubusercontent.com/12487823/89705468-085c1280-d934-11ea-982a-443ada1bacb1.png)

### MEKONG EYE - HOME
Layout dark mode: https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/421824059/preview?scrollOffset=3966.666748046875 
- [x] Header without background image has to follow dark mode
![image](https://user-images.githubusercontent.com/12487823/89681734-e5961380-d8cb-11ea-8450-5cdeeb0a1528.png)

- [ ] Group blocks in Home must follow dark mode layout
![image](https://user-images.githubusercontent.com/12487823/89700611-e64b9b80-d905-11ea-8059-9556922e9715.png)

- [x] Mekong Eye must use a logo for Dark mode. So, it must be included in the Customize panel.
![image](https://user-images.githubusercontent.com/12487823/89700917-da150d80-d908-11ea-9c14-d9e76c2d5155.png)

### PASIFIKA
Follow dark mode version: 
https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/421825053/inspect?scrollOffset=3966.666748046875

- [x] The pasifika's newsletter uses a css "newsletter-pasifika". 
![image](https://user-images.githubusercontent.com/12487823/89705395-69371b00-d933-11ea-832c-4b9fdb429ee0.png)

- [x] Footer must use a logo dark
![image](https://user-images.githubusercontent.com/12487823/89705421-a8656c00-d933-11ea-9f6d-1890a6ee624b.png)

- [x] In sidebar, 'follow us' has color black. It should be white
![image](https://user-images.githubusercontent.com/12487823/89705786-596d0600-d936-11ea-9df4-08f49b95749b.png)

- [x] **toolbar**
Include menu more as Language
https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/421655020/inspect?scrollOffset=3966.666748046875

![image](https://user-images.githubusercontent.com/12487823/89706271-773c6a00-d93a-11ea-8f0f-fab3f215539e.png)

- [x] Error console editor
![image](https://user-images.githubusercontent.com/12487823/89720577-d5ecfc80-d9a9-11ea-8dec-917d445744c3.png)

**Comment by isaquemelo** [comment]
This is error is being generated by a Gutenberg script. Initially, we can't do anything.
![image](https://user-images.githubusercontent.com/7103838/89893440-bb37a500-dbae-11ea-9465-bbc9305eae0e.png)
![image](https://user-images.githubusercontent.com/7103838/89893555-f2a65180-dbae-11ea-8719-cb77c835cf0e.png)
