### ISSUE TITLE
[ Most read widget ] Minor fixes

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#120]
- [x] The most read widget is not working for tags
https://mekongeye-jeo.hacklab.com.br/tag/asia/

- [x] The most read widget MUSN'T appear if it doesn't have enough posts.

![image](https://user-images.githubusercontent.com/12487823/89703731-caef8900-d923-11ea-990e-2a7599737770.png)

**Comment by isaquemelo** [comment]
Dependencies fulfilled. 
Tags page with most read widget when only a single post is available:
limit 1:
![image](https://user-images.githubusercontent.com/7103838/89895275-e96ab400-dbb1-11ea-9426-3028572928d1.png)
limit 3:
![image](https://user-images.githubusercontent.com/7103838/89895384-161ecb80-dbb2-11ea-9441-481c5a50da93.png)
