### ISSUE TITLE
[ Menu Hamburguer ] minor fixes

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#129]
- [x] when I reach to the top of the page, making the sticky header to not go away after I close the menu
- [x] It looks odd on Firefox for Windows and in posts on Chrome as well:
![image](https://user-images.githubusercontent.com/12487823/89812035-e3bf9080-db15-11ea-915c-f4f00f918f90.png)

**Comment by isaquemelo** [comment]
Topic 1 should be fixed with #119
