### ISSUE TITLE
[ Post Template ]  Featured photo (large) below excerpt

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#130]
- [x] When featured image is = LARGE , the excerpt must be above that image
![image](https://user-images.githubusercontent.com/12487823/89891310-39924800-dbab-11ea-8f8d-ed669e275916.png)

- [x] Dark mode - bug no bloco 'read more' no Ekuatorial home
![image](https://user-images.githubusercontent.com/12487823/89926505-63636300-dbdb-11ea-85fd-4887de7f29c5.png)

**Comment by isaquemelo** [comment]
The ekuatorial block should have the class home__newsletter-bkg.
