### ISSUE TITLE
[ Comment Form ] Improve UX and UI

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#131]
**Alignment** ( done by Pamela)
bug:
![image](https://user-images.githubusercontent.com/12487823/90391966-655a7580-e064-11ea-9a0c-8d34ab8b327b.png)

POST REGULAR
- [x] Related posts section and Newsletter horizonta aligned with footer - DEFAULT TEMPLATE (ok)
- [x] Related posts section and Newsletter horizonta aligned with footer - ONE COLUMN (ok)
- [x] Related posts section and Newsletter horizonta aligned with footer - ONE COLUMN WIDE (ok)

POST OPINION
- [x] Related posts section and Newsletter horizonta aligned with footer - DEFAULT TEMPLATE (ok)
- [x] Related posts section and Newsletter horizonta aligned with footer - ONE COLUMN (ok)
- [x] Related posts section and Newsletter horizonta aligned with footer - ONE COLUMN WIDE (ok)
![image](https://user-images.githubusercontent.com/12487823/90356685-b8add300-e026-11ea-9db7-d4d0d870b4d8.png)

**Comment Form**
- [x] User should be able to move between fields with tab keyboard key; (OK)
- [ ] We should have a tool like Akismet set to prevent spam, with its needed privacy disclosure;
- [x] After commenting, window should move to the comment itself, instead of going to the top; (OK)
- [x] How will this section be if we have several comments. Should we bring pagination or “load more” to show all comments?; (OK)
- [x] It would be nice if the “Reply” button had an icon to represent that, like it is with email clients;  (OK)
- [ ] It would be nice to allow visitors to like/dislike comments so they are sorted based on number of likes. Could be done with the plugin https://wordpress.org/plugins/comments-like-dislike/  (OK partially)
- [ ] A theme hook to sort comments;
- [ ] Comments need a bit of design work;
I wonder if comments shouldn’t be above the comment form

- [ ] We need to style the screen "Duplicate comment detected". Can this and other error messages appear within the comment area? Here’s the page that opens: https://mekongeye-jeo.hacklab.com.br/wp-comments-post.php. This shows up when a duplicate comment is detected.

![image](https://user-images.githubusercontent.com/12487823/90028858-90be1880-dc90-11ea-9a95-f846413c699d.png)

**Comment by isaquemelo** [comment]
branch **_feature/comments-form_**

**Comment by isaquemelo** [comment]
Enable comments pagination to paginate comments.
![image](https://user-images.githubusercontent.com/7103838/90247335-bcfea400-de0c-11ea-91d8-76e3cb97c439.png)

**Comment by isaquemelo** [comment]
"We should have a tool like Akismet set to prevent spam, with its needed privacy disclosure;" - need to be installed in the desired sites.
"A theme hook to sort comments;" - the layout doesn't predict a sorting area/button.
"Comments need a bit of design work; I wonder if comments shouldn’t be above the comment form" - still following layout directives. TBD.

**Comment by pamelars86** [comment]
I pushed these changes in your branch :

**Alignment** ( done by Pamela)
POST REGULAR
- [x] Related posts section and Newsletter horizontal aligned with footer - DEFAULT TEMPLATE
- [x] Related posts section and Newsletter horizontal aligned with footer - ONE COLUMN
- [x] Related posts section and Newsletter horizontal aligned with footer - ONE COLUMN WIDE

POST OPINION
- [x] Related posts section and Newsletter horizontal aligned with footer - DEFAULT TEMPLATE
- [x] Related posts section and Newsletter horizontal aligned with footer - ONE COLUMN
- [x] Related posts section and Newsletter horizontal aligned with footer - ONE COLUMN WIDE
![image](https://user-images.githubusercontent.com/12487823/90356685-b8add300-e026-11ea-9db7-d4d0d870b4d8.png)
