### ISSUE TITLE
[ New Blocks ] minor fixes

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#136]
- [x] Bloco ‘Imagem com slider’: on fullscreen images should still show legend and credits
- [x] could icons at the top right be a little bigger?
- [x] Bloco ‘Imagem com crédito’: credits and icon should follow the same grid and height

**Comment by isaquemelo** [comment]
The transitions weren't made initially, it would take some time to implement transitions.
