### ISSUE TITLE
[ Dark mode ] Home

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#137]
### MEKONG EYE - HOME
Layout dark mode: https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/421824059/preview?scrollOffset=3966.666748046875 
- [x] The Mekong eye's newsletter section in Home was built with the Gutenberg block. However, it must follow the dark mode layout
![image](https://user-images.githubusercontent.com/12487823/89700658-5f4af300-d906-11ea-931d-e796e2bcaf89.png)

### PASIFIKA
Follow dark mode version: 
https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/421825053/inspect?scrollOffset=3966.666748046875

- [x] Header. Eu acho que precisamos outra imagem png
![image](https://user-images.githubusercontent.com/12487823/89705226-f5484300-d931-11ea-9412-55ae990ec623.png)

**Comment by isaquemelo** [comment]
New customizer options have been added to accomplish new dark mode possibilities.
