### ISSUE TITLE
[ Home ] Without new blocks

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#166]
**Layout Desktop Light** 
https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/425170275/preview?scrollOffset=3966.666748046875

**Layout Desktop Dark** 
https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/427833524/preview?scrollOffset=3966.666748046875

**Layout Mobile** 
https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/425326106/preview?scrollOffset=3966.666748046875

**Layout Mobile Dark** 
https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/427834635/preview?scrollOffset=3966.666748046875

**To do**
- [x] Create dump file with home structure and some posts

Update home.scss if it is needed
- [x] updated header
![image](https://user-images.githubusercontent.com/12487823/91110429-3770c480-e654-11ea-9936-8fc557172bfa.png)

![image](https://user-images.githubusercontent.com/12487823/91110487-5cfdce00-e654-11ea-887b-6de50072380d.png)

- [x] Add font-size and typography for menu
MekongEye : 14px
Pasifika, Ekuatorial, InfoAmazonia: 16px
![image](https://user-images.githubusercontent.com/12487823/91111164-2c1e9880-e656-11ea-94ac-12e49ec185d6.png)

New Field: "menu font" (it doesnt need to upload a new typography). If it is empty, the primary-font is used.

![image](https://user-images.githubusercontent.com/12487823/91115048-b3243e80-e65f-11ea-97b7-f33996cfb198.png)

**Comment by isaquemelo** [comment]
- updated header (ok)
- add font-size and typography for menu (ok)

**Comment by isaquemelo** [comment]
- [ ] Dark-mode card category color:
![image](https://user-images.githubusercontent.com/7103838/91200331-68450e00-e6d5-11ea-830f-fb4796212b8c.png)
