### ISSUE TITLE
[ Gutenberg Block ] Tooltip component

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#168]
- [x] Create new block "tooltip"

![image](https://user-images.githubusercontent.com/12487823/91206606-ce359380-e6dd-11ea-916f-3cbf71133da4.png)

Exemplo: TheIntercept.com/2019/10/21/ibama-bilhoes-multas-ambientais (termo Fundo Amazônia)

**Comment by isaquemelo** [comment]
branch _**feature/tooltip**_

**Comment by pamelars86** [comment]
**Observação 1**
Ao adicionar o tooltip
![image](https://user-images.githubusercontent.com/12487823/91370621-3cb14900-e7e5-11ea-84ea-444d8e08d481.png)

a 1eira vez que eu adiciono o ":", acontece o seguinte:

![image](https://user-images.githubusercontent.com/12487823/91370634-46d34780-e7e5-11ea-9c1a-ca2b22f5d8cb.png)


o workaround: colocando por 2da vez os ":" dentro do bloco tooltip

![image](https://user-images.githubusercontent.com/12487823/91370698-6b2f2400-e7e5-11ea-967b-2441593ccc1b.png)


**Observação 2**

Em um momento apareceu esse erro mas não sei se foi porque faltou carregar algum js, não aconteceu novamente
![image](https://user-images.githubusercontent.com/12487823/91370741-88fc8900-e7e5-11ea-9abc-7326982916b9.png)

**Comment by pamelars86** [comment]
**Observação 3**

Deveria fechar o tooltip ao clicar fora da palavra (como é feito no intercept). Atualmente para fechar o tooltip no celular é preciso clicar novamente na palavra
![image](https://user-images.githubusercontent.com/12487823/91371699-15a84680-e7e8-11ea-9896-297fe90a4551.png)
