### ISSUE TITLE
[ Newspack block ]  Update homepage article block

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#175]
Layout: https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/425170275/preview?scrollOffset=3966.666748046875

**To do**
- [x] Add an icon on the right bottom corner of homepage block ( from Newspack ). This icon will have these features: 
- background (primary color)
- color white
- icon from FontAwesome

Ex.
![image](https://user-images.githubusercontent.com/12487823/90848878-5580b100-e344-11ea-8403-1ebdfec1f00f.png)

![image](https://user-images.githubusercontent.com/12487823/90848886-59acce80-e344-11ea-9062-b87a9db80ada.png)

- [x] Include the "region" (or country) above post's title

![image](https://user-images.githubusercontent.com/12487823/90849016-b0b2a380-e344-11ea-814d-9a049a69f7d8.png)

- [x] Post with type = AUDIO. When featured photo is off, will be shown as image below
![image](https://user-images.githubusercontent.com/12487823/90851581-8f08ea80-e34b-11ea-98df-6dc63b014898.png)

- [x] Post with type = OPINION. _I think it is possible to do with newpack block_
![image](https://user-images.githubusercontent.com/12487823/91063539-842caf00-e604-11ea-8874-9efc3b87be7d.png)

**Comment by isaquemelo** [comment]
branch **_feature/article-block_**

**Comment by isaquemelo** [comment]
The primary category (yoast selector) is always shown
![image](https://user-images.githubusercontent.com/7103838/91061788-90177180-e602-11ea-8ae0-1a7520901efd.png)
