### ISSUE TITLE
[ Post Regular ] Update styles css for Sorry Block and Newsletter

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#189]
Layout: https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/425489726/preview?scrollOffset=3966.666748046875

- [x] Update sorry block
![image](https://user-images.githubusercontent.com/12487823/90849508-c83e5c00-e345-11ea-8cee-892b4624e4a3.png)

- [x] Update newsletter horizontal
![image](https://user-images.githubusercontent.com/12487823/90849577-f58b0a00-e345-11ea-8712-be8feae8b0f8.png)

**Some fixes**
Alinhamento vertical do bloco gutenberg "newsletter"
![image](https://user-images.githubusercontent.com/12487823/90909858-c956a400-e3ac-11ea-836e-5ff0b2d2833c.png)

**Comment by isaquemelo** [comment]
branch **_feature/sorry-newsletter_**

**Comment by pamelars86** [comment]
FIXED:

HORIZONTAL BLOCK
Button height = 66px
![image](https://user-images.githubusercontent.com/12487823/91063674-aaeae580-e604-11ea-8a52-13bd511d007e.png)

HORIZONTAL WIDGET
![image](https://user-images.githubusercontent.com/12487823/91063779-c81fb400-e604-11ea-84fb-9a08a4fd4267.png)
