### ISSUE TITLE
[ Post Editor ] There will be 2 options: "show authors" and "show author bio"

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#194]
- [x] Add a new option "show author(s)" to show/hide author metadata (Ex. By <user>.

- [x] Update the "author show bio" option to show/hide ONLY the author's biography section

Validação: No Twitter (se “show authors” estiver ON, mostrar twitters).

**Comment by isaquemelo** [comment]
branch **_feature/post-editor_**
