### ISSUE TITLE
[ Bugs ] 25/08

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#205]
- [x] JEO plugin's buttons aren't appearing in Ekuatorial
![image](https://user-images.githubusercontent.com/12487823/91120592-66933000-e66c-11ea-9928-4ec536fb49f2.png)

- [x] Translate "see last edition" phrase in newsletter widget
![image](https://user-images.githubusercontent.com/12487823/91168405-f7d5c700-e6ab-11ea-8c83-1c8add2f35fe.png)

- [x] External link icon isnot appearing

**Comment by isaquemelo** [comment]
Autoptimize inline css somehow breaks the JEO plugin buttons

**Comment by isaquemelo** [comment]
Dark mode external source on hover its not looking as expected 
![image](https://user-images.githubusercontent.com/7103838/91349594-e7147680-e7bb-11ea-9873-6884fff4896d.png)
