### ISSUE TITLE
[ Bugs - Search Results ] When user searches in the search modal, the results is not being ordered by "latest"

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#218]
The "latest" order is the default sort

Ver se esta usando a data de publicação ou de atualização
![image](https://user-images.githubusercontent.com/12487823/92011667-c9965e00-ed21-11ea-91e4-721a0e925c48.png)

Colocamos essa URL e deu certo
https://infoamazonia-jeo.hacklab.com.br/?s=brasil&order=DESC

**Comment by isaquemelo** [comment]
branch _**bugfix/search-order**_
