### ISSUE TITLE
[ Special Project ] Issues

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#236]
- [x] Add model template in Project Page: Default, One column, one column-width

- [x] The project page is broken when in the Customize Panel --> Template Settings
the Featured Image Default Position = Behind article title 
![image](https://user-images.githubusercontent.com/12487823/91906259-496aec80-ec7e-11ea-96b6-e9f953152068.png)
bug

![image](https://user-images.githubusercontent.com/12487823/91906322-5ee01680-ec7e-11ea-8b1b-382674cd8383.png)

**Comment by isaquemelo** [comment]
Branch **_bugfix/responsive_**
