### ISSUE TITLE
[Dark Mode]

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#25]
Dark mode: it’s possible to respect the visitors’ choice of using its device in the dark mode and show the website with a dark or light color theme

- [x] Web
- [x] Mobile

**Comment by isaquemelo** [comment]
branch **_feature/dark-mode_**

**Comment by isaquemelo** [comment]
If the user has a theme preference, the preference will be followed, unless the user changes using the mode buttons. If the user has changed the preference inside the site, this will ignore the theme preference defined in the system.

**Comment by isaquemelo** [comment]
`window.localStorage` is used for theme schema persisting. The way the data persists can is described at the following link: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
