### ISSUE TITLE
[ Home Responsive ] Melhorias no modo "ipad / tablet"

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#250]
### Low priority

- [x] Letra de newsletter muito grande
![image](https://user-images.githubusercontent.com/12487823/91376642-ec8db300-e7f3-11ea-82ab-5df2943cbdb6.png)

- [ ] Home: Bastante espaço em branco, da para evitar?
![image](https://user-images.githubusercontent.com/12487823/91376682-03cca080-e7f4-11ea-853a-abd96db261f1.png)
![image](https://user-images.githubusercontent.com/12487823/91376716-1515ad00-e7f4-11ea-9acf-a0eaf3381349.png)

- [ ] Colunas não estão bem divididas
![image](https://user-images.githubusercontent.com/12487823/91376764-35de0280-e7f4-11ea-8a2f-37ab128cd221.png)

- [ ] Manter o slogan na direita do logo
![image](https://user-images.githubusercontent.com/12487823/91376998-cfa5af80-e7f4-11ea-8d6a-d1a330430d53.png)

- [ ] Arrumar botão "subscribe" do mekong eye

![image](https://user-images.githubusercontent.com/12487823/91377044-dcc29e80-e7f4-11ea-872f-390983e85634.png)

SAFARI

-  On Safari the photo behind a quote element won't keep the Parallax effect
-  Background parallax images don't work well on Safari and are cut out on any browser – please check BBC reference again on mobile to see how they solved it: https://www.bbc.co.uk/news/resources/idt-sh/made_up_to_look_beautiful_sent_out_to_die 

Stefano's comment (27/07/2020)
E considerando que o Edge agora usa o mesmo engine do Chrome, não precisamos testar em mais nenhum navegador para computador. No celular e tablet, acho que tem que testar mesmo só no Safari para iOS (visto que os demais navegadores usam o mesmo engine) e no Chrome e Firefox para Android (já que os demais navegadores são quase todos baseados no engine do Chrome). E quando falamos do Firefox no Android, a não ser que seja um problema muito grosseiro, podemos considerar só o Firefox Beta. A versão de produção do Firefox não recebe novos recursos há uns meses e vai ser substituída pelo Beta muito brevemente.

**Tools**
http://bbc.github.io/device-switcher/#device=desktop

**Comment by willowmagrini** [comment]
@bwstefano algumas áreas em branco estão ocorrendo porque resumos de notícias estão sendo ocultadas na versão para tablet. 
Podemos exibir estes resumos?

**Comment by bwstefano** [comment]
@willowmagrini, acabei deixando isso passar... Vi que os resumos agora estão aparecendo, certo? Ficou melhor.

**Comment by willowmagrini** [comment]
@bwstefano podemos considerar essa issue concluida?

**Comment by bwstefano** [comment]
@willowmagrini, ainda há dois problemas pendentes: o item "Colunas não estão bem divididas" continua igual e o efeito Parallax continua não funcionando no Safari.

**Comment by willowmagrini** [comment]
Conforme conversamos no telegram fizemos um ajuste no CSS do mekongeye para manter a coluna da direita com 33%
"Colunas não estão bem divididas" antes:
![image](https://user-images.githubusercontent.com/8497431/129352999-d88e93b8-a519-4142-ad61-c436fc0f216b.png)
Depois:
![image](https://user-images.githubusercontent.com/8497431/129353075-78f90bcf-71bc-4dee-b7cb-0db1c332409e.png)
