### ISSUE TITLE
[Image Gallery] Drag and Drop photos in Editor. Add degrade in mobile

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#268]
- [x] Image Gallery Editor: Drag and Drop das fotos (reordenar)

![image](https://user-images.githubusercontent.com/12487823/100350043-1065be00-2fc8-11eb-8feb-8a5c0bd4c881.png)

- [x] Image Gallery Mobile: Sugestões para indicar ao usuário que existem mais fotos: Degradê na direita das fotos para incentivar o mover para os lados (mais simples)

![image](https://user-images.githubusercontent.com/12487823/100912257-ff78e900-34ae-11eb-94f2-074445347dec.png)

**Comment by leopiccionia** [comment]
I opened two separate PRs: #366 and #370.
