### ISSUE TITLE
[ Team block ] Make the team block in Post Editor more similar to team block in Front End

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#270]
*Back End*
- This part needs some improvements to look like Front End

![image](https://user-images.githubusercontent.com/12487823/101159676-87283a00-360c-11eb-82c5-dffa1fb1ec5d.png)

*Front End*
Example: [here](https://dev.infoamazonia.org/sobre/)

![image](https://user-images.githubusercontent.com/12487823/101159340-0bc68880-360c-11eb-838b-add04ee39c82.png)

**Comment by hockpond** [comment]
Branch: [feature/team-block-backend](https://github.com/EarthJournalismNetwork/jeo-theme/compare/feature/team-block-backend)

**Comment by pamelars86** [comment]
The "+" option is appearing between name and description which make difficult to edit
![Screenshot from 2020-12-09 19-06-00](https://user-images.githubusercontent.com/12487823/101694294-a500ff00-3a51-11eb-9d92-d9c6c1ec153d.png)

Cursor for name and description fields is not appearing
![Screenshot from 2020-12-09 19-06-53](https://user-images.githubusercontent.com/12487823/101694345-be09b000-3a51-11eb-8222-7d31236845a3.png)

**Comment by pamelars86** [comment]
@hockpond 

São fixes menores a serem feitos

No infoamazonia, como o team block vai ser usado dentro de uma coluna, ele fica assim:
![image](https://user-images.githubusercontent.com/12487823/102090587-675af800-3dfc-11eb-83eb-f6b433e8b15c.png)

Alguns ajustes a serem feitos SÓ aplicados no backend poderiam ser
- reduzir o padding laterais
- reduzir o margin-left do texto
- reduzir o tamanho do texto 

Veja por favor como aparece na tela "Sobre nós" do seu localhost (backup infoamazonia)
