### ISSUE TITLE
[ New Gutenberg block ] Image slider with grid and fullwidth buttons

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#28]
- [x] Image slider in desktop
https://projects.invisionapp.com/d/main#/console/19859607/425170275/preview

The image slider will have the grid option and fullwidth image. Also each image has the credits icon as it was implemented for post with featured image : "behind the title"
https://mekongeye-jeo.hacklab.com.br/2020/06/26/survivors-of-pnpc-dam-collapse-in-laos-flee-deteriorating-relocation-centers/
![image](https://user-images.githubusercontent.com/12487823/88333037-e775a980-cd05-11ea-95f5-b4c8ba438811.png)

NEW COMPONENT:
![image](https://user-images.githubusercontent.com/12487823/88332747-6ae2cb00-cd05-11ea-9559-da76bd77b603.png)

- [x] Image slider in Mobile
https://projects.invisionapp.com/share/GJY3O14DMK8#/screens

![image](https://user-images.githubusercontent.com/12487823/88561776-396c4700-d006-11ea-8985-6e701452f531.png)

Reference:
https://www1.folha.uol.com.br/equilibrioesaude/2020/03/quais-sao-os-sintomas-do-novo-coronavirus.shtml

**Comment by isaquemelo** [comment]
Branch **_feature/image-gallery_**

**Comment by isaquemelo** [comment]
The mobile layout couldn't be completely followed.

**Comment by pamelars86** [comment]
Minor bugs found:

DESKTOP:
1. Long descriptions don't fit in image slide
![image](https://user-images.githubusercontent.com/12487823/89343006-02d3a380-d67a-11ea-8c8e-80e1a8192dfe.png)

2. Image gallery in Cover block has a strange behaviour when user clicks on "grid"
![image](https://user-images.githubusercontent.com/12487823/89343073-1b43be00-d67a-11ea-9978-733a41b39409.png)

3.  Image gallery in Cover block breaks layout after clicking on "expand" button
![image](https://user-images.githubusercontent.com/12487823/89343089-24348f80-d67a-11ea-9e96-61533974786d.png)
