### ISSUE TITLE
[ Sidebar ] Menu with submenu is not shown correctly in sidebar

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#288]
Here:
https://mekongeye.iesech.info/
- [ ] Desktop. Submenu's options are not shown correctly
![image](https://user-images.githubusercontent.com/12487823/95094677-894f4480-0700-11eb-9254-4b28e9828048.png)

- [ ] Mobile, user can't see all menu & submenu's options because there is no vertical scroll
![image](https://user-images.githubusercontent.com/12487823/95094930-d59a8480-0700-11eb-994a-fe14b5912707.png)

**Comment by isaquemelo** [comment]
branch **_feature/fix-sub-menu-behavior_**
