### ISSUE TITLE
[ Google Fonts ] Load fonts locally instead of requestion from Google Fonts

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#311]
Notei que estamos puxando fontes do Google Fonts. Por questões de privacidade e para SEO, é melhor que a gente as sirva localmente. Aqui um guia de como fazer. E parece bem simples, mas não quero fazer eu mesmo para não perdermos o controle do que é instalado. https://complianz.io/self-hosting-google-fonts-for-wordpress/

**Comment by pamelars86** [comment]
19/11
Foi combinado que será feito o teste pelo @bwstefano

**Comment by bwstefano** [comment]
Executei o teste no dev.infoamazonia.org porque não tenho acesso a plugins no outro ambiente. Funcionou, mas ainda existe uma linha ```<link rel='dns-prefetch' href='//fonts.googleapis.com' />``` no HTML que não deveria estar lá.
