### ISSUE TITLE
[ Related Post ] Fix css in image

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#324]
- [x] Posts relacionados: falta ajustar imagem​. No celular, no modo paisagem, as imagens dos posts relacionados não estão seguindo o grid​
![image](https://user-images.githubusercontent.com/12487823/95903669-dc627080-0d6c-11eb-955f-8f326162a124.png)

**Comment by leopiccionia** [comment]
Does this issue still occur? I couldn't reproduce it in any mobile dimension.
