### ISSUE TITLE
[ Credited Image block ] This block must use 'credit' and 'description/caption' fields of image

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#349]
Mekong Eye: O bloco do tipo “Credited Image” não segue o padrão do WordPress ao não adicionar a legenda e os créditos da imagem que são vinculados à imagem no modal de mídias, fazendo com que o editor tenha que inserir a legenda direto no post. Além de gerar uma experiência de usuário ruim, o dado deixa de estar vinculado à imagem no banco de dados e vai atrapalhar a migração dos dados quando o site optar por trocar de tema.

![image](https://user-images.githubusercontent.com/12487823/99279861-79eb0d00-280f-11eb-905f-65ad57618219.png)

**Comment by pamelars86** [comment]
@bwstefano 

**Para lembrar que para as imagens destacada usamos os campos:**
- credit (que é do plugin Newspack credits): como crédito da foto
- description: como descrição da foto

**Para o bloco de "Imagem com crédito" estamos usando os campos**
- caption: como crédito da foto
- description: como descrição da foto
O bloco foi criado como um componente javascript e não tem acesso aos campos adicionais de outros plugins foi por isso que não conseguimos usar o campo 'credit'.

**Comment by bwstefano** [comment]
@pamelars86, ok. Não deixem de colocar isso na documentação para editores, por favor.
