### ISSUE TITLE
[ Author Page ] Layout is not showing social networks and image is too large

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#351]
Error:
![image](https://user-images.githubusercontent.com/12487823/100231565-f6fc3d80-2f05-11eb-8143-5563144b362f.png)

Correct layout
![image](https://user-images.githubusercontent.com/12487823/100231775-3dea3300-2f06-11eb-9232-e3b51da3feda.png)

**Comment by leopiccionia** [comment]
The issue can be divided in two:

* Author image is too large in some cases: for this, I opened PR #355.
* Social links are not showing: turning on social links in theme settings (requires Yoast) seems to fix this (see image below).

![image](https://user-images.githubusercontent.com/9576518/100270121-583c0500-2f36-11eb-9456-e95db87ea74b.png)
