### ISSUE TITLE
[ Auto fill ] Colocar suporte a AutoFill no campo de email para newsletter / comentários

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#352]
@hockpond 
Para o newsletter
É para colocar esse autocomplete=email, no form do mailchimp.

Para os comentários
Tem que ver o form de comentários dentro do tema e adicionar autocomplate=email

(só colocar um autocomplete="email" no input): https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill

Confirmar se aparece para os comentários

**Comment by pamelars86** [comment]
Useful link
https://developer.wordpress.org/reference/functions/comment_form/

**Comment by hockpond** [comment]
It seems to be working already

![image](https://user-images.githubusercontent.com/39286044/101526328-36497600-396b-11eb-96d6-27518aa4b8da.png)
![image](https://user-images.githubusercontent.com/39286044/101526456-655fe780-396b-11eb-8e95-3c53832f0220.png)
