### ISSUE TITLE
[ Featured image ] Large and Small featured image must include description/credit as credit image block

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#367]
Outra coisa que notei é que a featured image, quando definida como "Large" ou "Small", não mostra o campo de créditos como o bloco "Credited image", que é como tínhamos aprovado no layout. Aqui um exemplo: https://pasifika.news/2020/11/pmg-villagers-revive-shrinking-mangroves/

Layout [here](https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/417741849/preview?scrollOffset=371)

![image](https://user-images.githubusercontent.com/12487823/101199863-3fbda000-3644-11eb-8281-d345f6edddfb.png)

Fix done @hockpond 

![image](https://user-images.githubusercontent.com/12487823/101648449-94806280-3a18-11eb-838e-ecc7910ecad1.png)

![image](https://user-images.githubusercontent.com/12487823/101648484-9f3af780-3a18-11eb-91ff-1379db1abdb5.png)

**Comment by pamelars86** [comment]
@hockpond 

https://infoamazonia-jeo.hacklab.com.br/2020/08/27/the-rainforest-has-been-in-existence-for-at-least-55-million-years/

Está pegando o campo "credit" e não está mostrando o campo description
![image](https://user-images.githubusercontent.com/12487823/102086136-5ad3a100-3df6-11eb-8ad5-aa0415b61d2a.png)

**Comment by hockpond** [comment]
New issue to fix bug 2: #388
