### ISSUE TITLE
[ Most read wiget ] Fix to show posts according to category/tag correctly

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#368]
o Most Read desta página de categoria (https://pasifika.iesech.info/category/type/original/) está mostrando os Most Read de todo o site, e não só os desta categoria

**Comment by pamelars86** [comment]
@hockpond 
This fix was made in STW. Please could you check it?

**Comment by hockpond** [comment]
The changes in most read widget made in STW should fix this problem. However, the most read widget of this page is showing only posts acoording to its category. Is it really showing the website's most read posts?

![image](https://user-images.githubusercontent.com/39286044/101048064-1aa43100-3561-11eb-87b6-3e370e9f73d7.png)
