### ISSUE TITLE
[ Featured Image ] Featured Image options sometimes isn't saved properly

### ISSUE THREAD

**Issue by hockpond** [EarthJournalismNetwork/jeo-theme#388]
![image](https://user-images.githubusercontent.com/39286044/102118799-f416ad80-3e1e-11eb-9c15-0833c7fec130.png)

The first thought was that it was related to a plugin conflict or with Jeo theme. However, the bug still happens with newspack theme and only these plugins: 
![image](https://user-images.githubusercontent.com/39286044/102118742-e3663780-3e1e-11eb-97f8-4deba93570ee.png)

**Comment by pamelars86** [comment]
However,
In localhost, everything works well. We need to check why it works in localhot but not in other envs

**Comment by isaquemelo** [comment]
May be directly related to https://github.com/WordPress/gutenberg/issues/23078 and https://github.com/WordPress/gutenberg/issues/19600. 

I disabled the "Custom fields" panel in DEV and should be good to go.
