### ISSUE TITLE
[ Speed ] Improve speed in wordpress (LightHouse)

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#400]
- [x] Use minify files
- [x] The WebP Converter for media plugin can be removed if cloudflare is used

**Comment by pamelars86** [comment]
Credited Image block is not working correctly with Autoptimize

With Autoptimize
![image](https://user-images.githubusercontent.com/12487823/103818104-a3bdf480-5046-11eb-977b-75fa25002f80.png)

Without
![image](https://user-images.githubusercontent.com/12487823/103818190-c6e8a400-5046-11eb-9c39-699deb1d0190.png)

**Comment by isaquemelo** [comment]
> Credited Image block is not working correctly with Autoptimize
> 
> With Autoptimize
> ![image](https://user-images.githubusercontent.com/12487823/103818104-a3bdf480-5046-11eb-977b-75fa25002f80.png)
> 
> Without
> ![image](https://user-images.githubusercontent.com/12487823/103818190-c6e8a400-5046-11eb-9c39-699deb1d0190.png)

The print was made in a not configurated environment (autopmize settings are wrong breaking all javascript). After an analysis we find out that the actual "credited image" problem is not related to Autopmize, but to other block updates that broke the block saving method, PR refeers https://github.com/EarthJournalismNetwork/jeo-theme/issues/349
