### ISSUE TITLE
[ Ekuatorial ] User can't updated some categories (High Permission)

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#406]
Some findings from Rupert (EJN) here:
[EkuatorialCategories.pdf](https://github.com/EarthJournalismNetwork/jeo-theme/files/5793851/EkuatorialCategories.pdf)

**Comment by isaquemelo** [comment]
Aparentemente as atualizações estão funcionando agora
![image](https://user-images.githubusercontent.com/7103838/109658871-d582a180-7b45-11eb-9279-98d20fd1eada.png)
![image](https://user-images.githubusercontent.com/7103838/109658881-dadfec00-7b45-11eb-8578-7864b8e229c4.png)

**Comment by pamelars86** [comment]
Slugs:

https://wpml.org/forums/topic/using-the-same-category-and-tag-slugs-in-different-languages/

**Comment by pamelars86** [comment]
17/03/2021

@bwstefano 

**Bug:** It is not possible to edit slug 'Bencana alam'

**Reason**:

- slugs are shared by Tags and Categories. There is already a tag called 'Bencana alam' so we can't reuse that slug in a category.


![image](https://user-images.githubusercontent.com/12487823/111411920-353a8a00-86ba-11eb-9722-be5752627bf6.png)

![image](https://user-images.githubusercontent.com/12487823/111411937-3b306b00-86ba-11eb-8a66-1a39365d297b.png)

**Comment by bwstefano** [comment]
This solved the problem and you may now close this issue, @pamelars86. Thanks.
