### ISSUE TITLE
[ External Source ] External source link with URL ending in special characters avoids Media Partner name appears correctly

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#414]
**Bug**

![image](https://user-images.githubusercontent.com/12487823/106023947-0d5d7b80-60a6-11eb-9344-7a8cf2e21cb0.png)

External source link:
https://vnanet.vn/en/tin-tuc/society-1007/mekong-delta-province-provides-housing-land-for-poor-households-3721481.html#

**Fix**
External source link - fixed (without "#")
https://vnanet.vn/en/tin-tuc/society-1007/mekong-delta-province-provides-housing-land-for-poor-households-3721481.html

**Comment by isaquemelo** [comment]
PR https://github.com/EarthJournalismNetwork/jeo-theme/pull/415
