### ISSUE TITLE
[  GDPR ] Use GoogleFonts locally in order to accomplish GDPR rules

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#418]
GDPR and Google Fonts:
https://complianz.io/google-fonts-and-gdpr-does-it-work/
https://complianz.io/self-hosting-google-fonts-for-wordpress/ 

In those links suggest that we should self-host our Google Fonts using this plugin:
OMGF | Optimize My Google Fonts
https://wordpress.org/plugins/host-webfonts-local/

**Comment by isaquemelo** [comment]
Setting example:
[OMGF ‹ InfoAmazonia — WordPress.pdf](https://github.com/EarthJournalismNetwork/jeo-theme/files/5926816/OMGF.InfoAmazonia.WordPress.pdf)

**Comment by isaquemelo** [comment]
The setting is individual for each site, when published setup every single one of them

**Comment by bwstefano** [comment]
This duplicates issue #311. Please bear in mind [this particular comment](https://github.com/EarthJournalismNetwork/jeo-theme/issues/311#issuecomment-735042673).
