### ISSUE TITLE
[ Homepage posts ] Remove type icon in fullwidth mode

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#431]
Não mostrar o ícone quando o bloco homepage posts é usado como background fullwidth

Bug

![image](https://user-images.githubusercontent.com/12487823/109042248-bbad0e80-76ae-11eb-823d-549838e0d494.png)

**Comment by isaquemelo** [comment]
PR https://github.com/EarthJournalismNetwork/jeo-theme/pull/449
