### ISSUE TITLE
[ Latest Post Block ] Publishing Failed

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#432]
@bwstefano, It is related to Cloudflare configuration. We had similar problem in our env in the past, we solved that changing our cloudflare's config. Since, cloudflare blocks Wordpress's API REST requests sometimes.

**Mekong Eye's env**

![image](https://user-images.githubusercontent.com/12487823/109073587-57517580-76d5-11eb-9c5b-1914b814b1fe.png)

**In our dev env** 
Page with Latest Post Block is published correctly

![image](https://user-images.githubusercontent.com/12487823/109074078-042bf280-76d6-11eb-8d04-d0cd825192f7.png)

**Comment by bwstefano** [comment]
@pamelars86, I've checked this Ray ID on Cloudflare and was able to find which rule was being triggered by WAF:

![image](https://user-images.githubusercontent.com/11841075/109090758-4ebb6800-76f2-11eb-810a-25af4ebba02e.png)

I was then able to use this block, so I'm closing this issue.
