### ISSUE TITLE
[ Sidebar and bottom Toolbar in Mobile ] 3 options: type size, share, darkmode

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#48]
- [x] Add options in menu sidebar (hamburguer icon) and update its style according to layout
https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/419727653/preview?scrollOffset=3966.666748046875

![image](https://user-images.githubusercontent.com/12487823/86524878-6f2e6d80-be56-11ea-92da-3d1cae40c985.png)

- [x] Add fixed toolbar in mobile mode
https://projects.invisionapp.com/d/main?origin=v7#/console/19859607/421659534/preview?scrollOffset=3966.666748046875
![image](https://user-images.githubusercontent.com/12487823/86524896-9c7b1b80-be56-11ea-9734-8471febc70aa.png)

- [x] Share button of the bottom toolbar must open native apps

**Comment by isaquemelo** [comment]
branch **_feature/user-customization_**

**Comment by isaquemelo** [comment]
The native share buttons will only work in **HTTPS** environments, due to browser restriction.

**Comment by isaquemelo** [comment]
Dark mode button adds "dark-theme" class to the body. This will be used for #25.

**Comment by pamelars86** [comment]
Add conditional:
If there are no menu selected for menu option in sidebar, the title language and any option MUSN'T be shown.
bug:
![image](https://user-images.githubusercontent.com/12487823/89453665-fdd42a00-d735-11ea-8c72-49f06c995cd5.png)
