### ISSUE TITLE
[ Video Gallery ]  New component

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-theme#59]
- [x] Video Gallery in Desktop
![image](https://user-images.githubusercontent.com/12487823/87710566-4a9e9380-c77c-11ea-940a-d444ae5cce91.png)
https://projects.invisionapp.com/d/main#/console/19859607/425170275/preview
Quando selecionados na listagem lateral, os vídeos da galeria de vídeos devem abrir na área de vídeo maior, substituindo o vídeo grande da galeria.

- [x] Video Gallery in mobile
Horizontal scroll
When user clicks on any video in the carrousel, it replaces the largest video of the gallery.
https://projects.invisionapp.com/share/GJY3O14DMK8#/screens
![image](https://user-images.githubusercontent.com/12487823/88558969-a2ea5680-d002-11ea-807b-a1b10345c545.png)

**Testes**
DESKTOP
- [ ] Video Gallery in Home
- [x] Video Gallery in Video Post
- [x] Video Gallery in Regular Post

MOBILE
- [ ] Video Gallery in Home
- [x] Video Gallery in Video Post
- [x] Video Gallery in Regular Post

We found 2 bugs
- [x] Reusable block 
- [x] Conflict with Cookie plugin @isaquemelo 
![image](https://user-images.githubusercontent.com/12487823/90267716-538e8d80-de2c-11ea-97cf-27e50d8579f0.png)

![image](https://user-images.githubusercontent.com/12487823/90277780-9193ad80-de3c-11ea-851e-a9e40f538887.png)

**Comment by isaquemelo** [comment]
branch **_feature/video-gallery_**

**Comment by pamelars86** [comment]
We found 2 bugs
- [x] Reusable block 
- [ ] Conflict with Cookie plugin @isaquemelo 
![image](https://user-images.githubusercontent.com/12487823/90267716-538e8d80-de2c-11ea-97cf-27e50d8579f0.png)
